language: php
php:
  - "5.6"

before_script:
- git config user.name "Travis-CI"
- git config user.email "builds@travis-ci.org"

jobs:
  include:
    - stage: test
      script: make
    - stage: deploy
      script:
        - set -e
        - git clone https://${github_username}:${github_token}@github.com/vilniusphp/vilniusphp.github.io.git
        - make
        - cp -a public_html/. vilniusphp.github.io
        - cd vilniusphp.github.io
        - git add .
        - git commit -m "Build new website version"
        - git push origin master

stages:
  - test
  - name: deploy
    if: (branch = master) AND (NOT (type IN (pull_request)))
