vilnius_php_library:
    resource: "@VilniusPHPLibraryBundle/Controller/"
    type:     annotation
    prefix:   /

vilnius_php_user:
    resource: "@VilniusPHPUserBundle/Controller/"
    type:     annotation
    prefix:   /

vilnius_php_events:
    resource: "@VilniusPHPEventsBundle/Controller/"
    type:     annotation
    prefix:   /

vilnius_php_core:
    resource: "@VilniusPHPCoreBundle/Controller/"
    type:     annotation
    prefix:   /

