<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130418191111 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE book (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, subtitle VARCHAR(255) DEFAULT NULL, edition VARCHAR(50) DEFAULT NULL, author VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, homepage VARCHAR(255) DEFAULT NULL, cover VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE book_owner (user_id INT NOT NULL, book_id INT NOT NULL, INDEX IDX_C1A2F305A76ED395 (user_id), INDEX IDX_C1A2F30516A2B381 (book_id), PRIMARY KEY(user_id, book_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE book_owner ADD CONSTRAINT FK_C1A2F305A76ED395 FOREIGN KEY (user_id) REFERENCES book (id)");
        $this->addSql("ALTER TABLE book_owner ADD CONSTRAINT FK_C1A2F30516A2B381 FOREIGN KEY (book_id) REFERENCES fos_user (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE book_owner DROP FOREIGN KEY FK_C1A2F305A76ED395");
        $this->addSql("DROP TABLE book");
        $this->addSql("DROP TABLE book_owner");
    }
}
