<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130630165837 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE book_comment CHANGE review review TINYINT(1) NOT NULL");
        $this->addSql("ALTER TABLE book ADD slug VARCHAR(255) NOT NULL");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_CBE5A331989D9B62 ON book (slug)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP INDEX UNIQ_CBE5A331989D9B62 ON book");
        $this->addSql("ALTER TABLE book DROP slug");
        $this->addSql("ALTER TABLE book_comment CHANGE review review TINYINT(1) DEFAULT '0' NOT NULL");
    }
}
