parameters:
    core.markdown_config:
        no_html: true

services:
    markdown.parser.custom:
        class: Knp\Bundle\MarkdownBundle\Parser\Preset\Max
        arguments: ['%core.markdown_config%']
